source: src/
url: http://127.0.0.1/
socket_url: http://127.0.0.1:8080/
destination: ./public_html/

future: true
lsi: false
markdown: maruku
permalink: /:title

nav:
- page: Home
  permalink: /
- page: Articles
  permalink: /articles/
- page: About
  permalink: /about/